### ISSUE TITLE
Force git to use SSH on GitHub

### ISSUE THREAD

**Issue by glevine** [glevine/machine#6]
Multiverse and Mango depend on private repositories. This is pretty common. SSH must be used.

https://ricostacruz.com/til/github-always-ssh

```
# me.yml
- include_role:
      name: git
    vars:
      configurations:
        ...
        - { name: url."git@github.com:".insteadOf, value: https://github.com/ }
        ...
```
